# Generated by Django 2.2.2 on 2019-06-30 14:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default=None, upload_to=accounts.models.user_id),
        ),
    ]
